CANALES_DEFAULT = ["@anthropologies", 
"@AstronomiayCiencia", "@CAFtv",
"@cienciamania", "@cienciamundana",
"@cienciaparatodos", "@cienciatelegram",
"@circuloesceptico", "@CosasdemiMundo",
"@cosmosastronomia", "@Darkspace",
"@EarthquakesWorld", "@fotovoltaica", "@fdomotica",
"@Gif_science", "@imagen_astronomica",
"@ingenieriaengeneral", "@laneuronacuriosa",
"@laquimeradegupta", "@microsiervos",
"@NanoFrames", "@quesecuece",
"@QuinteScience", "@reporteespacial",
"@Science", "@SistemaSolar",
"@SOSTENIBLE132", "@torhispano",
"@articaonline", "@brigadaCultural",
"@canalusb", "@fundacomunes",
"@nativacat", "@tipicodeandalucia",
"@trazosdeaprendizaje",
"@artesmarciales_now", 
"@MundoArtesMarciales",
"@MTBMountainBike", "@Notibici",
"@FitnessLiving", "@gimnasioyfitness",
"@habitossaludablesfit", 
"@canalpasaporte", "@cincomaseldescuento",
"@cristalderocasenderismoyviajes", "t.me/DiarioSenderista",
"@escalada_climb_mountain", "@linkalicante",
"@senderismonosvamosderutamadrid",
"@senderismoyaventuravalencia", "@Senderrutas",
"@culturismo2", "@escacs", "@MLB_LATAM",
"@NBAtelegram", "@NewYork_Yankees",
"@Hocklife", "@yoguiman",
"@arquitecturasostenible", "@Artemisa_GR",
"@avatarenergia", "@blogsostenible",
"@DIY_hazlotumismo", "@ecoinventos",
"@ecointeligencia", "@ecologia_medioambiente",
"@ecologistas", "@ecologistes",
"@EcologistasHuesca", "@EeA_Salamanca",
"@eficiencia_energetica", "@energias_renovables_DIY",
"@EsXrebellion", "@eXtinctionRebellion",
"@fffmadrid", "@Futuro_Renovable",
"@goiener", "@GPMadrid",
"@greenpeace_esp", "@Huerto_ecologico",
"@ideasverdes", "@Jauziekosoziala",
"@lmclimatica", "@medioambiente_info",
"@reducir", "@ResiduoCero",
"@solar_energia", "@vehiculos_electricos",
"@XRMadrid",
"@bolsayeconomia", "@carrodecombate",
"@CNMV_HR", "@colectivoburbuja", "@economiabolsayfinanzas",
"@forex_se", "@ForexFaiv",
"@insiderprodigest", "@lascaldastr",
"@logoserviciosfinancieros", "@mercadosocialmadrid",
"@PromocionesBancariasFintech", "@rmcsignalsfree",
"@TradingForexSPE", "@tradinglatino_senales",
"@tradinglatinoprivado", "@tradingsignalsarg", "@carpinteria_aficionados",
"@Cursos_Digitales_Full_Gratis", "@cursosenpdf",
"@cursosfullmega", "@cursosmegadrive6",
"@DarwinEventur", "@Diccionarioletras",
"@docente_innovador", "@educacion",
"@educacion3_0", "@educaciontecnologica",
"@enfermeriaucihgcr", "@filosofiayemociones",
"@formacionib", "@formantic",
"@gvaEducacio", "@habitossaludables",
"@indautocontrol", "@IngenieriaLibrosPDF",
"@LaSendadelCriminologo", "@MunicionEducativa",
"@Ortografiando", "@Primaria_Bol",
"@profesoradodesecundaria", "@profesoresdeBolivia",
"@psicoencuentrocuba", "@robotica",
"@Sexualidad_Emociones",
"@aliadas_TransFem", "@AmoryFeminismo",
"@arribalasbarriguitas", "@asamblea8mzaragoza",
"@Asturies8M", "@AssembleafeministaVlc",
"@azadijinconvos", "@barbijaputa",
"@bibliotecafeministabot", "@bilbofeministasaretzen",
"@comuneras", "@DeMentesFeministas",
"@DonesLleida", "@espaciofeministaBC",
"@FeminismoFemNosotras", "@feminismos",
"@Ibarlucea", "@NafarroakoM8",
"@MujeresRadfem", "@pikaramagazine",
"@pnitas_ilustracion", "@PQTVeas",
"@VisionGlobal8M", "@vivesirebels",
"@abyayalalaotrahistoria", "@antrophistoria",
"@buzzhistory", "@capsulahistoria",
"@HistoCast", "@HistoriayArqueologia",
"@historyfacts", "@historyporn_eng",
"@MemoriaLibertariaCGT", "@MuyFan36",
"@oudeis_es",
"@c_v_360", "@CanalMotor",
"@CyR_MotorNews", 
"@formula1newses3", "@Formuleros",
"@RACEFANS_F1", "@motolife",
"@my_cars", "@noticias_F1",
"@rally",
"@animalpolitico", "@antonigr",
"@barricadatv", "@bestnoticias",
"@CanalRed_TV", "@CanalVientoSur",
"@cnnee", "@colombiainforma",
"@CongresodelosDiputados", "@CanalREDCOM",
"@cronicasjudiciales1", "@cubadebate",
"@DescifrandolaGuerra", "@diariodetransporte",
"@DWnoticiasenEsp",
"@elpaisuruguay", "@ElProfeRomero",
"@eltoquecom", "@ElUniversalOnline",
"@ESS_REAS", "@EstebanConcia",
"@Euronews_Noticias", "@bermeoezkerretik",
"@FuentePolicialOficial",
"@Interprofesional", "@kaoscanal",
"@La_Patilla", "@ladiaria",
"@laguacamayaroja", "@lajirafanoticiera",
"@laneuronarebelde", "@LopezDorigaCom",
"@nafarroainfo", "@NoticieroPolitico",
"@NOTMEX", "@NYTimes_Noticias",
"@periodistadigit", "@prensaobrera",
"@pressenza", "@RDNDigital",
"@Red_Voltaire", "@RevistaAlmaMater",
"@revistahamartia", "@Riberanoticias",
"@RPDCorea", "@runrunes",
"@sentitcritic", "@sinembargomx",
"@susogg", "@TerceraGuerraMundial_TGM",
"@Terrorismo_Internacional", "@tomalosmedios",
"@TudelaHoy", "@Vocesdecuenca",
"@bcnencomu", "@CatComu",
"@ComudeLleida", "@comuns_info",
"@encomupodem", "@ganar_mostoles",
"@MasMadridCM", "@premsaECP",
"@somcomuns",
"@arran_jovent", "@cupcapgirembcn",
"@cupnacional",
"@consumogob", "@iunida",
"@jovenesiu",
"@PartidoPiratadeChile", "@PirataCat",
"@Partido_Popular", "@ppmadrid",
"@canalPSOE", "@psoeleon",
"@ahorapodemos", "@AndaluciaPodemos",
"@CANALFeministaPodemita", "@canalpodemcatalunya",
"@eltoparlamentu", "@euskadipodemos",
"@NoticiasPodemosCanarias", "@PodemosCLM",
"@PodemosCMadrid", "@podemoscyl",
"@podemosexterior", "@podemosextremadura",
"@podemosgalicia", "@podemosinter",
"@PodemosLeganes", "@podemosmadrid",
"@podemosparla", "@PodemosRegionMurcia",
"@podemossa", "@PodFemEstatal",
"@PTTNN", "@RevistaPrensaPodemosAsturies",
"@SecretariaDeEconomia", "@SOEPodemos",
"@alternativarepublicana", "@antikapitalistak",
"@bloquenacionalistagalego", "@compromis",
"@CsCiudadanos", "@EsquerdaUnida",
"@esquerrarepublicana", "@juntsxcat",
"@VOXtelegram",
"@andaluciarepublicana", "@anticapitalistasmov",
"@CongresodelosDiputados", "@cubadecide",
"@ecorepublicano", "@EDITOnfiRe",
"@electomania", "@entre_guerras",
"@fundacomunes", "@geoestrategia1",
"@juventuduce",
"@latizadecuba", "@martinezpower",
"@monarquiaespana", "@nacionandaluza",
"@Naranja_bogota", "@news1906",
"@NoveJuntaEdu", "@nuevo_orden_mundial_canal",
"@politicaobrera", "@quincem",
"@RedObservadores", "@SalamancaEnAccion",
"@SinPermisoinfo", "@XnetInfo",
"@ADLGarrotxa", "@ANC_Mossos",
"@ANC_Reus", "@ancaltemporda",
"@ANCCassa", "@anccentelles",
"@ancConca", "@ANCEsparreguera",
"@ancgirona", "@ancpolinya",
"@ancsantceloni", "@ANCsantcugat",
"@anctarragona", "@ANCTrsxlaindepe",
"@anoncatalonia", "@assemblea",
"@aturemelpais", "@AturemDiagonalPgGracia",
"@barrisants1o", "@CanalRepublica",
"@CDR_Catalunya", "@cdr_la_marina",
"@cdrgironasalt", "@cdrlleida",
"@CDRReus", "@cdrvalldellemena",
"@ClotDecideix", 
"@GironaVota", "@independentcatalonia",
"@lalerta", "@omnium",
"@omniumeixample", "@premiaenmarxa",
"@tutenslaforca", "@UACDE",
"@AdaColau", "@AlbertoGarzon",
"@clara_serra", "@emmanuelmacron",
"@evasolla",
"@ierrejon", "@irenegomez",
"@Isabel_franco", "@jorgemoruno",
"@juralde",
"@Kitos_Cant", "@LorenaRuizHuerta",
"@markserra", "@Monedero",
"@NeskutzPodemos", "@ObispoPauloRoberto",
"@PabloEchenique", "@pascualsergio",
"@pilarlima", "@PresidenteAMLO",
"@Raimundo_Viejo", "@sofcastanon",
"@albatv", "@ANRed",
"@BBCes", "@cordopolis",
"@ctxtes", "@diariogetxo",
"@elboletin", "@elcomun",
"@eldiariocyl", "@eldiarioes",
"@eldiarioescan", "@elnacionalcat",
"@elperiodico", "@elsaltodiario",
"@elsaltoextremaduracanal", "@elsaltomadrid",
"@guilhotinainfo", "@hordago_elsalto",
"@infobae", "@kaosenlared",
"@maldita_es", "@malditobulo",
"@naciodigital", "@naiz_info",
"@newtral_telegram", "@noticias_20minutos",
"@nytimes", "@periodismodigital",
"@poder_popular", "@publico_es",
"@RevistaLaMarea", "@segovianews",
"@aahispano", "@av5dres",
"@canalceliaco", "@casestatal",
"@cbdhoy", "@CienciasMedicas",
"@conlasaludnosejuega", "@coronavirus_noticias",
"@conterapiasnaturales", "@desarrollopersonalcuba",
"@diabetes_es", "@Discapacitados",
"@DISFAM",
"@enferme", "@enfermeriaucihgcr",
"@enfermeriatecnologica", "@enfermerosquirofanoalcazar",
"@intensivistapediatrico", "@laanatomiaefacil",
"@medicinahistoria", "@minsapcuba",
"@PreClic", "@psicologia_esp",
"@saludnutricionydeporte", "@salutcat",
"@sanidadgob", "@sicologia",
"@tuvidamasnatural", "@urgenciasyemergencias",
"@vidasaludybienestar", "@cisegnews",
"@Emergenciasnacionales", "@EmergenciasSevilla",
"@guardianesdelasfalto", "@InteligenciaPolicial",
"@inteligenciayliderazgo", "@MovilidadGranada",
"@policememes", "@policianacional",
"@policias", "@wakinakipolicialocal",
"@canalccoo", "@ccooajb",
"@canalccooaragon", "@CGTCorreos",
"@CGTfesibac", "@cgtzonasur",
"@cigbbva", "@cnt_ait",
"@cntcordoba", "@cntensenanza", "@cntvalladolid",
"@CSI_ArcelorMittal", "@FSIECyL",
"@InformaticaCGT", "@mrafundazioa",
"@noticias_correos", "@noticiasCNT",
"@sindicatostecyl", "@SoliObrera",
"@SomosSindicalistasCAM", "@UGT_ArcelorMittal",
"@ugt_es", "@UGTcomite",
"@UJP_UGT_Gijon", "@vozobrera",
"@ZaragozaCNT",
"@ADSLzoneNet", "@amalialopezacera",
"@arepatecnologica", "@asociacion",
"@blogarmandof", "@CanalResistenciaDigital",
"@cupontech", "@DescargasDirectas",
"@domoticaencasa", "@Educacion3_0","@feminismo_y_tecnologia",
"@ferchtech", "@geektalenews",
"@genbeta", "@ieofficial",
"@kodiadictosnoticias", "@micommes",
"@microsiervos",
"@NoticiasTecnologia", "@programarfacilc",
"@salmorejogeek", "@SeguridadInformatic4",
"@seo30", "@Servidores",
"@sistemastelecomunicaciones",
"@tecnolocura", "@telemorse",
"@tendenciatecnologica", "@ugeek",
"@ulinks", "@unocero",
"@URE_ES", "@wificanarias",
"@Wired_Noticias", "@xataka",
"@XatakaMexico", "@XnetInfo",
"@AndaluciaJunta", "@andaluciarepublicana",
"@NoveJuntaEdu", "@tipicodeandalucia",
"@AlmeriaNoticias", "@museoalmeria",
"@alsondelcarnaval", "@AyuntamientodeConil",
"@cepjerez", "@codigocarnaval",
"@jereznoticias",
"@puentegenil",
"@AyuntamientodeBaza", "@ayuntamientolasgabias",
"@difusion_bshq", "@huetorvega",
"@MovilidadGranada",
"@agendahuelva", "@AljaraqueConsumo",
"@AljaraqueCultura", "@AljaraqueDesarrolloLocal",
"@AytoGalaroza", "@EmpleOnubA",
"@horajaen", "@Linares_al_dia",
"@ayuntamientobenalmadena", "@AyuntamientoCampillos",
"@ayuntamientocanillasdeaceituno", "@ayuntamientodecartama",
"@ayuntamientodenerja", "@aytobenarraba",
"@AytoMontecorto", "@harastepa",
"@iTorrox", "@jubrique",
"@ayuntamientodesevilla", "@AyuntamientoGuadalcanal",
"@ayuntamientopalomaresdelrio", "@elebrija",
"@EmergenciasSevilla", "@infoaytoElCoronil",
"@gobiernoaragon",
"@AyuntamientoFraga",
"@alcaniz_deportes",
"@AytoTarazona", "@Ayuntamiento_Maluenda",
"@panizainforma",
"@CatalunyaMeteo", "@meteolook",
"@ajcanetdemar", "@ajelprat",
"@ajfolgueroles", "@ajlagranada",
"@AjPoblaLillet", "@ajpremiademar",
"@AjSabadell", "@ajsantceloni",
"@ajseva", "@AjuntamentBadalona",
"@AjuntamentdeManresa", "@AjuntamentdeTordera",
"@ajvacarisses", "@BcnAjuntament",
"@difusiocsacanvies", "@VallcarcaVKK",
"@ajuntamentdefigueres", "@ajuntamentdegirona",
"@ajuntamentflaca", "@ajuntamentporqueres",
"@infoquart", "@santjaumedellierca",
"@SarriadeTer",
"@AjOrganya", "@lleidadiari",
"@ajborgesdelcamp", "@ajvilaplana",
"@botarell", "@rodadebera",
"@gvaEducacio", "@tresdeu",
"@ajuntamentelx", "@Ampareyes",
"@AyuntamientodeCalp", "@AyuntamientodeSantaPola",
"@aytoelda", "@aytoraspeig",
"@beneixama", "@policiaelche",
"@policiaelchetrafico", "@ReyesCatolicosDireccion",
"@ajlavallduixo", "@AjuntamentVinaros",
"@ayuntamientodesonejainfo",
"@AyuntamientoOlocaudelReyInforma",
"@Belllloc", "@benicarlo",
"@casalpopularvr", "@conservatoriosuperiorcastellon",
"@infoValldalba", "@lesuseres",
"@lopedevegacastellon",
"@ajuntamassanassa", "@ajuntamentdecullera",
"@AjuntamentdeSueca", "@AjuntamentVallada",
"@AyuntamientodeTorrent", "@ayuntamientotorrebaja",
"@aytogatova", "@AytoSanAntonioDeBenageber",
"@bansajuntamentderiola", "@bansenyera",
"@ClauAgenda", "@estivellaajuntament",
"@Forta2020", 
"@AlcantarillaalDia", "@aytoalhama",
"@aytocartagenaes", "@AytoLorca",
"@aytolaroda", "@aytoyecla",
"@ayuntamientodelosalcazares", "@noticiasaytosanjavier",
"@puertolumbreras", "@ResiduoCeroRM"]